# Generated by Codex on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="fulfillment_method",
            field=models.CharField(
                choices=[("delivery", "Delivery"), ("pickup", "Pickup")],
                default="delivery",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_location",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="order",
            name="preferred_delivery_window",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_location",
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
