# Generated by Django 5.2.16 on 2026-07-07 15:48

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('mpesa', 'M-Pesa')], default='mpesa', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=8)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('receipt_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('result_code', models.CharField(blank=True, max_length=32)),
                ('result_description', models.TextField(blank=True)),
                ('raw_request', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('raw_callback', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'status'], name='payments_pa_provide_cc7861_idx'), models.Index(fields=['checkout_request_id'], name='payments_pa_checkou_e4cf10_idx'), models.Index(fields=['merchant_request_id'], name='payments_pa_merchan_d33a1b_idx')],
            },
        ),
    ]
